# This file has been generated by node2nix 1.8.0. Do not edit!

{nodeEnv, fetchurl, fetchgit, globalBuildInputs ? []}:

let
  sources = {
    "fsevents-2.1.3" = {
      name = "fsevents";
      packageName = "fsevents";
      version = "2.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/fsevents/-/fsevents-2.1.3.tgz";
        sha512 = "Auw9a4AxqWpa9GUfj370BMPzzyncfBABW8Mab7BGWBYDj4Isgq+cDKtx0i6u9jcX9pQDnswsaaOTgTmA5pEjuQ==";
      };
    };
  };
in
{
  "rollup-2.28.1" = nodeEnv.buildNodePackage {
    name = "rollup";
    packageName = "rollup";
    version = "2.28.1";
    src = fetchurl {
      url = "https://registry.npmjs.org/rollup/-/rollup-2.28.1.tgz";
      sha512 = "DOtVoqOZt3+FjPJWLU8hDIvBjUylc9s6IZvy76XklxzcLvAQLtVAG/bbhsMhcWnYxC0TKKcf1QQ/tg29zeID0Q==";
    };
    dependencies = [
      sources."fsevents-2.1.3"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "Next-generation ES module bundler";
      homepage = https://rollupjs.org/;
      license = "MIT";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
}